USE [master]
GO
/****** Object:  Database [TKB]    Script Date: 14/04/2025 10:42:50 SA ******/
CREATE DATABASE [TKB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TKB', FILENAME = N'C:\HequantriCSDL\TKB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TKB_log', FILENAME = N'C:\HequantriCSDL\TKB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TKB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TKB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TKB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TKB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TKB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TKB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TKB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TKB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TKB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TKB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TKB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TKB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TKB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TKB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TKB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TKB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TKB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TKB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TKB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TKB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TKB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TKB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TKB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TKB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TKB] SET RECOVERY FULL 
GO
ALTER DATABASE [TKB] SET  MULTI_USER 
GO
ALTER DATABASE [TKB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TKB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TKB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TKB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TKB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TKB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TKB', N'ON'
GO
ALTER DATABASE [TKB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TKB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TKB]
GO
/****** Object:  Table [dbo].[GiaoVien]    Script Date: 14/04/2025 10:42:50 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GiaoVien](
	[MaGV] [varchar](5) NOT NULL,
	[HoTen] [nvarchar](50) NULL,
 CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
(
	[MaGV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LopHocPhan]    Script Date: 14/04/2025 10:42:50 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LopHocPhan](
	[MaLHP] [varchar](5) NOT NULL,
	[Tenlop] [varchar](10) NULL,
 CONSTRAINT [PK_LopHocPhan] PRIMARY KEY CLUSTERED 
(
	[MaLHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MonHoc]    Script Date: 14/04/2025 10:42:50 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MonHoc](
	[MaMH] [varchar](7) NOT NULL,
	[TenMH] [nvarchar](100) NULL,
 CONSTRAINT [PK_MonHoc] PRIMARY KEY CLUSTERED 
(
	[MaMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TKB]    Script Date: 14/04/2025 10:42:50 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TKB](
	[MaTKB] [varchar](5) NOT NULL,
	[MaGV] [varchar](5) NULL,
	[MaLHP] [varchar](5) NULL,
	[MaMH] [varchar](7) NULL,
	[PhongHoc] [varchar](7) NULL,
	[Thu] [int] NULL,
	[TietBD] [int] NULL,
	[SoTiet] [int] NULL,
	[GioVao] [time](0) NULL,
	[GioRa] [time](0) NULL,
	[NgayHoc] [date] NULL,
 CONSTRAINT [PK_TKB] PRIMARY KEY CLUSTERED 
(
	[MaTKB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_GiaoVien] FOREIGN KEY([MaGV])
REFERENCES [dbo].[GiaoVien] ([MaGV])
GO
ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_GiaoVien]
GO
ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_LopHocPhan] FOREIGN KEY([MaLHP])
REFERENCES [dbo].[LopHocPhan] ([MaLHP])
GO
ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_LopHocPhan]
GO
ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_MonHoc] FOREIGN KEY([MaMH])
REFERENCES [dbo].[MonHoc] ([MaMH])
GO
ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_MonHoc]
GO
USE [master]
GO
ALTER DATABASE [TKB] SET  READ_WRITE 
GO
